spring.application.name=oneride

spring.datasource.url=jdbc:postgresql://localhost:5432/one_ride_db
spring.datasource.username=reddy
spring.datasource.password=7816

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=reddy
spring.security.user.password=oneride

# JWT Configuration
jwt.secret=OneRideSuperSecretKeyForJwtAuthentication2026OneRideSecureKey
jwt.expiration=86400000